version: '3.7'

services:
  piwigo:
    image: linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - VIRTUAL_HOST=bilder.stefan-hoenes.de
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=bilder.stefan-hoenes.de
      - LETSENCRYPT_EMAIL=stefan@hoenes-gerlingen.de
    volumes:
      - piwigo:/config
    expose:
      - '80'
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - piwigo-db

  piwigo-db:
    container_name: piwigo-db
    hostname: piwigo-db
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - piwigo-db:/var/lib/mysql
	  - /var/lib/docker/volumes/nextcloud/_data/data/Bilder/files/Bilder:/config/www/gallery/galleries/:ro
    environment:
      MYSQL_DATABASE: piwigo
      MYSQL_USER: piwigo
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - backend

  netshoot:
    image: nicolaka/netshoot
    container_name: netshoot
    hostname: netshoot
    restart: unless-stopped
    command: "tail -f /dev/null"
    networks: 
      - backend

  mysql-client:
    image: widdpim/mysql-client
    container_name: mysql-client
    hostname: mysql-client
    restart: unless-stopped
    command: "tail -f /dev/null"
    networks: 
      - backend


volumes:
  piwigo:
    external: true
  piwigo-db:
    external: true

networks:
  backend:
    external:
      name: backend
