version: '3.7'

services:
  piwigo:
    image: linuxserver/piwigo
    container_name: piwigo
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - VIRTUAL_HOST=bilder.stefan-hoenes.de
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=bilder.stefan-hoenes.de
      - LETSENCRYPT_EMAIL=stefan@hoenes-gerlingen.de
    volumes:
      - /path/to/appdata/config:/config
    expose:
      - '80'
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - piwigo-db

  piwigo-db:
    container_name: piwigo-db
    hostname: piwigo-db
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - piwigo-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: piwigo
      MYSQL_USER: piwigo
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - backend


networks:
  backend:
    external:
      name: backend
