version: '3.7'

services:
  openvpn-as:
    image: linuxserver/openvpn-as
    container_name: openvpn-as
    hostname: openvpn-as
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - INTERFACE=enp2s0
    volumes:
      - openvpn-config:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped
    networks:
      - vpn

volumes:
  openvpn-config:
    external: true

networks:
  vpn:
    external:
      name: vpn


