scrape_configs:
- job_name: 'node'
  scrape_interval: 30s
  static_configs:
  - targets: ['docker-host:9100']
- job_name: cadvisor
  scrape_interval: 30s
  static_configs:
  - targets:
    - cadvisor:8080
