version: '3.7'

services:

  nextcloud:
    container_name: nextcloud
    hostname: nextcloud
    # image: nextcloud:fpm-alpine
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=nextcloud-redis
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    networks:
      - backend
    expose:
      - '9000'

  nextcloud-redis:
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - nextcloud-redis:/data
    networks:
      - backend

  nextcloud-db:
    container_name: nextcloud-db
    hostname: nextcloud-db
    image: postgres:alpine
    restart: unless-stopped
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - nextcloud-db:/var/lib/postgresql/data
    networks:
      - backend

  nextcloud-onlyoffice:
    container_name: nextcloud-onlyoffice
    hostname: nextcloud-onlyoffice
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: unless-stopped
    expose:
      - '80'
      - '443'
    volumes:
      - nextcloud-onlyoffice:/var/lib/onlyoffice
      - nextcloud-onlyoffice_data:/var/www/onlyoffice/Data
      - nextcloud-onlyoffice_log:/var/log/onlyoffice
      - nextcloud-onlyoffice_postgresl:/var/lib/postgresql
      - nextcloud-onlyoffice_truetype:/usr/share/fonts/truetype/custom
    networks:
      - backend

  nextcloud-web:
    container_name: nextcloud-web
    hostname: nextcloud-web
    image: nginx
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=nextcloud.stefan-hoenes.de
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=nextcloud.stefan-hoenes.de
      - LETSENCRYPT_EMAIL=stefan@hoenes-gerlingen.de
    expose:
      - '80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nextcloud:/var/www/html
    networks:
      - backend


volumes:
  nextcloud:
    external: true
  nextcloud-redis:
    external: true
  nextcloud-db:
    external: true
  nextcloud-onlyoffice:
    external: true
  nextcloud-onlyoffice_data:
    external: true
  nextcloud-onlyoffice_log:
    external: true
  nextcloud-onlyoffice_postgresl:
    external: true
  nextcloud-onlyoffice_truetype:
    external: true

networks:
  backend:
    external:
      name: backend
